<div class="footer-main-container">
    <div class="footer-main">
        <div class="footer-section my-account">
            <div class="footer-section-title">
                My Account
            </div>

            <div class="footer-section-items">
                <div class="footer-section-item">
                    My account
                </div>
                <div class="footer-section-item">
                    Personal information
                </div>
                <div class="footer-section-item">
                    Payment methods
                </div>
                <div class="footer-section-item">
                    Orders history
                </div>
                <div class="footer-section-item">
                    Payment options
                </div>
                <div class="footer-section-item">
                    Discount
                </div>
            </div>
        </div>

        <div class="footer-section customer-services">
            <div class="footer-section-title">
                Customer Servises
            </div>

            <div class="footer-section-items">
                <div class="footer-section-item">
                    Help  & contact
                </div>
                <div class="footer-section-item">
                    Shipping & taxes
                </div>
                <div class="footer-section-item">
                    Return policy
                </div>
                <div class="footer-section-item">
                    Privacy policy
                </div>
                <div class="footer-section-item">
                    What’s new
                </div>
                <div class="footer-section-item">
                    Affiliates
                </div>
            </div>
        </div>

        <div class="footer-section contact-details">
            <div class="footer-section-title">
                Contact Details
            </div>

            <div class="footer-section-items">
                <div class="footer-section-item-contact">
                    <div class="footer-section-item-contact-icon-container">
                        <div class="footer-section-item-contact-icon phone"></div>
                    </div>

                    <div class="footer-section-item-contact-data">
                        <div class="footer-section-item-contact-data-item">0203 - 980 - 14 - 79</div>
                        <div class="footer-section-item-contact-data-item">0203 - 478 - 12 - 96</div>
                    </div>
                </div>

                <div class="footer-section-item-contact">
                    <div class="footer-section-item-contact-icon-container">
                        <div class="footer-section-item-contact-icon email"></div>
                    </div>

                    <div class="footer-section-item-contact-data">
                        <div class="footer-section-item-contact-data-item">veme@gmail.com</div>
                        <div class="footer-section-item-contact-data-item">venedor@mail.com</div>
                    </div>
                </div>

                <div class="footer-section-item-contact">
                    <div class="footer-section-item-contact-icon-container">
                        <div class="footer-section-item-contact-icon skype"></div>
                    </div>

                    <div class="footer-section-item-contact-data">
                        <div class="footer-section-item-contact-data-item">venedor_contact</div>
                        <div class="footer-section-item-contact-data-item">venedor_support</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-section information">
            <div class="footer-section-title">
                Information
            </div>

            <div class="footer-section-items">
                <div class="footer-section-item">
                    New products
                </div>
                <div class="footer-section-item">
                    Top sellers
                </div>
                <div class="footer-section-item">
                    Specials products
                </div>
                <div class="footer-section-item">
                    Manufacturers
                </div>
                <div class="footer-section-item">
                    Suppliers
                </div>
                <div class="footer-section-item">
                    Manufacturers
                </div>
            </div>
        </div>

        <div class="footer-section instagram">
            <div class="footer-section-title">
                Instagram
            </div>

            <table class="footer-section-items-table">
                <tbody>
                    <tr>
                        <td><div class="footer-section-items-table-item"></div></td>
                        <td><div class="footer-section-items-table-item"></div></td>
                        <td><div class="footer-section-items-table-item"></div></td>
                    </tr>
                    <tr>
                        <td><div class="footer-section-items-table-item"></div></td>
                        <td><div class="footer-section-items-table-item"></div></td>
                        <td><div class="footer-section-items-table-item"></div></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="footer-bottom">
        <div class="footer-bottom-left">
            <div class="footer-bottom-left-title">
                100% Secure & Trusted Payment.
            </div>
            <div class="footer-bottom-left-subtitle">
                Need help? Call us at +0203-980-14-79 for any assistance required.
            </div>
        </div>

        <div class="footer-bottom-right">
            <div class="footer-bottom-right-icon mastercard"></div>
            <div class="footer-bottom-right-icon paypal"></div>
            <div class="footer-bottom-right-icon american-express"></div>
            <div class="footer-bottom-right-icon maestro"></div>
            <div class="footer-bottom-right-icon visa"></div>
        </div>
    </div>
</div>
