<div class="header-banner-khachidze-container">
    <div class="header-banner-khachidze">
        <div class="header-banner-khachidze__item">
            <div class="header-banner-khachidze__icon truck"></div>
            <div class="header-banner-khachidze__description">
                <div class="header-banner-khachidze__title">Free Delivery</div>
                <div class="header-banner-khachidze__subtitle">on orders over $100</div>
            </div>
        </div>

        <div class="header-banner-khachidze__divider"></div>

        <div class="header-banner-khachidze__item">
            <div class="header-banner-khachidze__icon gift"></div>
            <div class="header-banner-khachidze__description">
                <div class="header-banner-khachidze__title">choose a free gifts</div>
                <div class="header-banner-khachidze__subtitle">with every purchase</div>
            </div>
        </div>

        <div class="header-banner-khachidze__divider"></div>

        <div class="header-banner-khachidze__item">
            <div class="header-banner-khachidze__icon lock"></div>
            <div class="header-banner-khachidze__description">
                <div class="header-banner-khachidze__title">100% secure shopping</div>
                <div class="header-banner-khachidze__subtitle">mauris ac pulvinar </div>
            </div>
        </div>
    </div>
</div>
